---
- name: Crear un par de claves SSH para EC2
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Crear Key Pair en EC2
      amazon.aws.ec2_key:
        name: "mi_par_de_claves"
        state: present
        region: "us-east-1"
      register: keypair

    - name: Mostrar la salida de keypair
      debug:
        var: keypair

    - name: Guardar la clave privada en formato PEM en /pruebasawx
      copy:
        content: "{{ keypair.key.private_key }}"
        dest: "/pruebasawx/mi_par_de_claves.pem"
        mode: '0600'
      when: keypair.key is defined and keypair.key.private_key is defined
