- name: Deploy ECS task definition and service for Jenkins
  hosts: localhost
  tasks:
    - name: Crear una VPC
      amazon.aws.ec2_vpc_net:
        state: present
        region: us-east-1
        cidr_block: "10.0.0.0/16"
        name: "my-vpc"
      register: vpc_output

    - name: Crear una subred en la VPC
      amazon.aws.ec2_vpc_subnet:
        state: present
        region: us-east-1
        vpc_id: "{{ vpc_output.vpc.id }}"
        cidr: "10.0.1.0/24"  # Ajusta según sea necesario
        tags:
          Name: Jenkinss Subnet
      register: subnet_output
      

    - name: Crear un grupo de seguridad
      amazon.aws.ec2_group:
        name: "jenkins-sg"
        description: "Security group for Jenkins"
        vpc_id: "{{ vpc_output.vpc.id }}"
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: "0.0.0.0/0"  # Permitir acceso público en el puerto 8080
      register: sg_output

    - set_fact: 
        EcsClusterName: "YOUR_CLUSTER"
        SubnetId: "{{ vpc_output.subnets[0].id }}"  # Usar la primera subred de la VPC
        SecurityGroupId: "{{ sg_output.group_id }}"

    - name: Crear clúster de ECS
      community.aws.ecs_cluster:
        name: "{{ EcsClusterName }}"
        region: us-east-1
        state: present
    
    - name: Crear definición de tarea para Jenkins
      community.aws.ecs_taskdefinition:
        family: jenkins_from_ansible
        network_mode: awsvpc
        requires_compatibilities:
          - FARGATE
        cpu: 512
        memory: 1024
        containers:
          - name: jenkins
            essential: true
            image: "jenkins/jenkins:lts"
            portMappings:
              - containerPort: 8080
            environment:
              - name: JENKINS_OPTS
                value: "--httpPort=8080"
        state: present
        region: us-east-1
      register: task_output

    - name: Crear servicio ECS para Jenkins
      community.aws.ecs_service:
        state: present
        name: jenkins_from_ansible
        cluster: "{{ EcsClusterName }}"
        task_definition: "{{ task_output.taskdefinition['family'] }}:{{ task_output.taskdefinition['revision'] }}"
        desired_count: 1
        launch_type: FARGATE
        network_configuration:
          awsvpc_configuration:
            subnets:
              - "{{ SubnetId }}"
            security_groups:
              - "{{ SecurityGroupId }}"
            assign_public_ip: "ENABLED"
        region: us-east-1
      register: service_output

    - name: Mostrar estado del servicio
      debug: var=service_output.service.status

    - name: Mostrar nombre del servicio
      debug: var=service_output.service.serviceName

    - name: Mostrar ARN del servicio
      debug: var=service_output.service.serviceArn

    - name: Mostrar ARN del clúster
      debug: var=service_output.service.clusterArn
