- name: Deploy ECS task definition and service for Jenkins
  hosts: localhost

  tasks:
    - set_fact: EcsClusterName="YOUR_CLUSTER"

    - name: Crear clúster de ECS
      community.aws.ecs_cluster:
        name: "{{ EcsClusterName }}"
        region: us-east-1
        state: present
    
    - name: create task definition for Jenkins
      ecs_taskdefinition:
        containers:
        - name: jenkins
          cpu: 512  # Ajusta según tus necesidades
          essential: true
          image: "jenkins/jenkins:lts"  # Imagen pública de Jenkins en Docker Hub
          memory: 1024  # Ajusta según sea necesario
          portMappings:
          - containerPort: 8080  # Puerto por defecto para Jenkins
            hostPort: 8080
          environment:
          - name: "JENKINS_OPTS"
            value: "--httpPort=8080"  # Opciones de Jenkins
        state: present
        region: us-east-1
        family: jenkins_from_ansible  # Nombre de la familia de la definición de tarea
        requires_compatibilities:
          - FARGATE  # Requerido para usar Fargate
        network_mode: awsvpc  # Requerido para Fargate
        cpu: 512  # Requerido por Fargate
        memory: 1024  # Requerido por Fargate
      register: task_output    

    - name: Print details Task family and revision     
      debug:
        msg: "{{ task_output.taskdefinition['family'] }}:{{ task_output.taskdefinition['revision'] }}"

    - name: create ECS service
      ecs_service:
        state: present
        name: jenkins_from_ansible
        cluster: "{{ EcsClusterName }}"
        task_definition: "{{ task_output.taskdefinition['family'] }}:{{ task_output.taskdefinition['revision'] }}"
        desired_count: 1  
        region: us-east-1
        launch_type: FARGATE  # Especifica Fargate como tipo de lanzamiento
        network_configuration: {}  # Modo de red Fargate, sin especificar subnets ni security groups
      register: service_output
    
    - name: Service Status     
      debug: var=service_output.service.status
    
    - name: Service name 
      debug: var=service_output.service.serviceName

    - name: Service ARN
      debug: var=service_output.service.serviceArn

    - name: Cluster ARN 
      debug: var=service_output.service.clusterArn
